In [ ]:
import pandas as pd
import numpy as np

In [ ]:
npr=pd.read_csv("/content/npr.csv")

In [ ]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(max_df=0.95,min_df=2,stop_words='english')

In [ ]:
dtm= cv.fit_transform(npr['Article'])

In [ ]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

#**LDA**

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation

In [ ]:
lda=LatentDirichletAllocation(n_components=6,random_state=42)

In [ ]:
lda.fit(dtm)

LatentDirichletAllocation(n_components=6, random_state=42)

In [ ]:
len(cv.get_feature_names_out())

54777

In [ ]:
import random

In [ ]:
for i in range(10):
  random_word_id=random.randint(0,54776)
  print(cv.get_feature_names_out()[random_word_id])

vacuumed
cognition
whaley
tour
reheat
seconds
extremities
broiled
coliform
fletcher


In [ ]:
len(lda.components_)

6

In [ ]:
single_topic=lda.components_[0]

In [ ]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [ ]:
import numpy as np
arr=np.array([10,200,1])
arr

array([ 10, 200,   1])

In [ ]:
arr.argsort()

array([2, 0, 1])

In [ ]:
single_topic.argsort()[-10:]

array([31464, 54403,  8149, 36310, 10425, 33390, 36283, 22673, 42561,
       42993])

In [ ]:
top_word_indices = single_topic.argsort()[-10:]

In [ ]:
for index_value in top_word_indices:
  print(cv.get_feature_names_out()[index_value])

million
year
care
percent
company
new
people
health
said
says


In [ ]:
top_twenty_incidices=single_topic.argsort()[-20:]

In [ ]:
for index in top_twenty_incidices:
  print(cv.get_feature_names_out()[index])

states
pay
tax
insurance
state
000
companies
money
federal
government
million
year
care
percent
company
new
people
health
said
says


grab highest probability words per topic



In [ ]:
for index,topic in enumerate(lda.components_):
  print(f"THE TOP 15 WORDS FOR TOPIC #{index}")
  print([cv.get_feature_names_out()[index] for index in topic.argsort()[-15:]])
  print('\n')
  print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['000', 'companies', 'money', 'federal', 'government', 'million', 'year', 'care', 'percent', 'company', 'new', 'people', 'health', 'said', 'says']




THE TOP 15 WORDS FOR TOPIC #1
['war', 'house', 'security', 'russia', 'npr', 'government', 'reports', 'news', 'says', 'told', 'people', 'police', 'president', 'trump', 'said']




THE TOP 15 WORDS FOR TOPIC #2
['make', 'way', 'home', 'world', 'day', 'time', 'city', 'water', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




THE TOP 15 WORDS FOR TOPIC #3
['years', 'don', 'new', 'time', 'university', 'students', 'study', 'just', 'children', 'women', 'like', 'school', 'health', 'people', 'says']




THE TOP 15 WORDS FOR TOPIC #4
['vote', 'election', 'just', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




THE TOP 15 WORDS FOR TOPIC #5
['going', 've', 'says', 'life', 'don', 'music', 'new', 'way', 'really', 'time', 'know', 'think

In [ ]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [ ]:
dtm.shape

(11992, 54777)

In [ ]:
len(npr)

11992

In [ ]:
topic_results=lda.transform(dtm)

In [ ]:
topic_results

array([[1.79827178e-02, 7.01695372e-01, 2.64251451e-04, 2.64339598e-04,
        2.79528760e-01, 2.64559242e-04],
       [2.14267353e-02, 9.17826026e-01, 5.16236084e-04, 5.16103781e-04,
        5.91982950e-02, 5.16604043e-04],
       [3.84749793e-04, 7.19948874e-01, 3.84104797e-04, 3.84101091e-04,
        2.78512816e-01, 3.85354161e-04],
       ...,
       [4.67673961e-04, 1.84931953e-01, 1.75692052e-01, 6.22083841e-01,
        1.63559288e-02, 4.68551818e-04],
       [5.08137625e-04, 3.95312284e-02, 5.07295183e-04, 5.08938575e-04,
        9.58434562e-01, 5.09838667e-04],
       [3.37018939e-01, 2.98930623e-04, 3.85259664e-01, 2.98554833e-04,
        2.76825111e-01, 2.98799688e-04]])

In [ ]:
topic_results.shape

(11992, 6)

In [ ]:
topic_results[0]

array([1.79827178e-02, 7.01695372e-01, 2.64251451e-04, 2.64339598e-04,
       2.79528760e-01, 2.64559242e-04])

In [ ]:
topic_results[0].round(2)

array([0.02, 0.7 , 0.  , 0.  , 0.28, 0.  ])

In [ ]:
topic_results[0].argmax()

1

In [ ]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [ ]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 2])

In [ ]:
npr['Topic']=topic_results.argmax(axis=1)

In [ ]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      2

[11992 rows x 2 columns]